### ISSUE TITLE
Heater bed not heating with MPC branch

### ISSUE THREAD

**Issue by DrFate09** [YanceyA/danger-klipper-BE_doc_update#5]
I switched over to your branch from DK to test the MPC functionality. I was able to successfully perform the hotend calibration but unfortunately my heated bed will not heat up while performing the initial calibration. I also noticed that I cannot heat my bed at all when using your branch (I tried commenting out the MPC values and adding back in my normal PID values with no success). To solve the issue, I had to switch back to DK and now the bed is heating up again.

For context, I am using a Duet 6HC running Klipper. Here's my bed config (Keenovo 24V 400W):
```
[adc_scaled vref_scaled]
vref_pin: vref
vssa_pin: vssa

[heater_bed]
heater_pin: out0
sensor_type: Generic 3950
sensor_pin: vref_scaled:temp0
pullup_resistor: 2200
min_temp: -10
max_temp: 130
#heater_power: 400 #MPC-specific
```

Additonally, here is a screen capture of Mainsail where I am attempting to warm up my bed for MPC calibration.
https://youtu.be/Z5eF2itvif4

**Comment by YanceyA** [comment]
@DrFate09 I suggest you open this issue against the bleeding-edge-v2 branch, as that is where development will be for MPC. Just copy-paste this issue. For now I am going to close this as not resolved, not applicable.

I note there is a help ticket on the discord for your issue.
